# -*- coding: utf-8 -*-
"""Weekly project 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xp-fRGVh6u-8fA-dGHN33vbBJFqqA1yc
"""

pip install faker

from faker import Faker
import random
import pandas as pd

fake = Faker()

data = []

for i in range(10000):
    patient = {
        "Patient_ID": f"P{i+1:05d}",
        "Age": random.randint(20, 80),
        "Gender": random.choice(["Male", "Female"]),
        "Blood_Pressure": random.randint(80, 180),
        "Sugar_Level": random.randint(70, 200),
        "Cholesterol": random.randint(150, 300),
        "Heart_Rate": random.randint(60, 120)
    }
    data.append(patient)

df = pd.DataFrame(data)

df.to_csv("patient_data.csv", index=False)

print("Data generated successfully!")
print(df)

df.info()

df.isnull().sum()

display(df.describe())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 10))

plt.subplot(2, 3, 1)
sns.histplot(df['Age'], kde=True)
plt.title('Distribution of Age')

plt.subplot(2, 3, 2)
sns.histplot(df['Blood_Pressure'], kde=True)
plt.title('Distribution of Blood Pressure')

plt.subplot(2, 3, 3)
sns.histplot(df['Sugar_Level'], kde=True)
plt.title('Distribution of Sugar Level')

plt.subplot(2, 3, 4)
sns.histplot(df['Cholesterol'], kde=True)
plt.title('Distribution of Cholesterol')

plt.subplot(2, 3, 5)
sns.histplot(df['Heart_Rate'], kde=True)
plt.title('Distribution of Heart Rate')

plt.subplot(2, 3, 6)
sns.countplot(x=df['Gender'])
plt.title('Count of Gender')

plt.tight_layout()
plt.show()



"""### Summary Statistics for Patient Health Metrics

### Patient Risk Classification
"""

BLOOD_PRESSURE_HIGH = 140
BLOOD_PRESSURE_MEDIUM = 120
SUGAR_LEVEL_HIGH = 180
SUGAR_LEVEL_MEDIUM = 100
CHOLESTEROL_HIGH = 240
CHOLESTEROL_MEDIUM = 200

def classify_risk(patient):
    risk_score = 0

    if patient['Blood_Pressure'] >= BLOOD_PRESSURE_HIGH:
        risk_score += 2
    elif patient['Blood_Pressure'] >= BLOOD_PRESSURE_MEDIUM:
        risk_score += 1

    if patient['Sugar_Level'] >= SUGAR_LEVEL_HIGH:
        risk_score += 2
    elif patient['Sugar_Level'] >= SUGAR_LEVEL_MEDIUM:
        risk_score += 1

    if patient['Cholesterol'] >= CHOLESTEROL_HIGH:
        risk_score += 2
    elif patient['Cholesterol'] >= CHOLESTEROL_MEDIUM:
        risk_score += 1

    if risk_score >= 4:
        return 'High'
    elif risk_score >= 2:
        return 'Medium'
    else:
        return 'Low'

df['Risk_Category'] = df.apply(classify_risk, axis=1)

print("Patients classified into risk categories.")
display(df.head())

plt.figure(figsize=(8, 6))
sns.countplot(x='Risk_Category', data=df, palette='viridis', order=['Low', 'Medium', 'High'])
plt.title('Distribution of Patient Risk Categories')
plt.xlabel('Risk Category')
plt.ylabel('Number of Patients')
plt.show()

health_metrics = ['Blood_Pressure', 'Sugar_Level', 'Cholesterol', 'Heart_Rate']

for metric in health_metrics:
    print(f"\n--- {metric} ---")
    display(df[metric].describe())

"""### Identifying High-Risk Patients"""

high_risk_patients = df[df['Risk_Category'] == 'High']

print(f"Number of High-Risk Patients: {len(high_risk_patients)}")
display(high_risk_patients.head())

"""### Group-based Analysis

### Relationship Between Variables
"""

plt.figure(figsize=(18, 6))

plt.subplot(1, 3, 1)
sns.scatterplot(x='Age', y='Blood_Pressure', data=df, hue='Risk_Category', palette='coolwarm', alpha=0.7)
plt.title('Blood Pressure vs Age')
plt.xlabel('Age')
plt.ylabel('Blood Pressure')

# Cholesterol vs Heart Rate
plt.subplot(1, 3, 2)
sns.scatterplot(x='Heart_Rate', y='Cholesterol', data=df, hue='Risk_Category', palette='viridis', alpha=0.7)
plt.title('Cholesterol vs Heart Rate')
plt.xlabel('Heart Rate')
plt.ylabel('Cholesterol')

# Sugar Level vs Risk Category (using box plot for distribution)
plt.subplot(1, 3, 3)
sns.boxplot(x='Risk_Category', y='Sugar_Level', data=df, order=['Low', 'Medium', 'High'], palette='plasma')
plt.title('Sugar Level Distribution by Risk Category')
plt.xlabel('Risk Category')
plt.ylabel('Sugar Level')

plt.tight_layout()
plt.show()

# Define age groups
age_bins = [0, 30, 45, 60, 75, 100]
age_labels = ['<30', '30-44', '45-59', '60-74', '75+']
df['Age_Group'] = pd.cut(df['Age'], bins=age_bins, labels=age_labels, right=False)

print("Distribution of patients by Age Group:")
display(df['Age_Group'].value_counts().sort_index())

print("\nAverage health metrics by Age Group:")
display(df.groupby('Age_Group')[['Blood_Pressure', 'Sugar_Level', 'Cholesterol', 'Heart_Rate']].mean())

print("Average health metrics by Gender:")
display(df.groupby('Gender')[['Blood_Pressure', 'Sugar_Level', 'Cholesterol', 'Heart_Rate']].mean())

print("\nRisk category distribution by Gender:")
display(pd.crosstab(df['Gender'], df['Risk_Category'], normalize='index'))

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
sns.countplot(x='Age_Group', hue='Risk_Category', data=df, palette='coolwarm', order=age_labels)
plt.title('Risk Category Distribution by Age Group')
plt.xlabel('Age Group')
plt.ylabel('Number of Patients')

plt.subplot(1, 2, 2)
sns.countplot(x='Gender', hue='Risk_Category', data=df, palette='coolwarm')
plt.title('Risk Category Distribution by Gender')
plt.xlabel('Gender')
plt.ylabel('Number of Patients')

plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 8))
sns.heatmap(df[health_metrics].corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix of Health Metrics')
plt.show()